path: "configs/aruco.launch"
type: "xml"
name: "aruco launch file"
description: ""
# additional info?
# parent_service: "clover"

options:
    aruco_detect:
        description: ""
        tree_path: ["./arg[@name='aruco_detect']", "attrib", "default"]
        type: "bool"
        default: False

    aruco_map:
        description: ""
        tree_path: [ "./arg[@name='aruco_map']", "attrib", "default" ]
        type: "bool"
        default: False

    aruco_vpe:
        description: ""
        tree_path: [ "./arg[@name='aruco_vpe']", "attrib", "default" ]
        type: "bool"
        default: False

    placement:
        description: ""
        tree_path: ["./arg[@name='placement']", "attrib", "default"]
        type: "enum"
        default: "floor"
        items:
            floor:
                description: "On the floor"
                # format may be extended to include some other fields
            ceiling:
                description: ""
            unknown:
                description: ""

    length:
        description: ""
        tree_path: [ "./arg[@name='length']", "attrib", "default" ]
        type: "float"
        default: 0.22
        gt: 0

    map:
        description: ""
        tree_path: [ "./arg[@name='map']", "attrib", "default" ]
        type: "str"
        default: "map.txt"
