path: "configs/aruco.launch"
type: "xml"
name: "aruco launch file"
description: ""
# additional info?
# parent_service: "clover"

options:
    aruco_detect:
        description: ""
        tree_path: ["./arg[@name='aruco_detect']", "attrib", "default"]
        type: "bool"
        default: False

    placement:
        description: ""
        tree_path: ["./arg[@name='placement']", "attrib", "default"]
        type: "enum"
        default: "floor"
        items:
            floor:
                description: "On the floor"
                # format may be extended to include some other fields
            ceiling:
                description: ""
            unknown:
                description: ""
