repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: debug-statements
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/psf/black
    rev: "21.11b1"
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: "v5.9.3"
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations~=2.0
          - flake8-bandit~=2.1
          - flake8-docstrings~=1.5
        args: [--max-line-length=120]
#        args: [--max-line-length=120, --ignore=ANN101 D107 ANN102 ANN206 D105 ANN204]
